# -*- coding: utf-8 -*-
"""project2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bY36CEro3X7w4_jI5GOwxqZKQmX16Wq

DIE ROLLING SIMULATOR
"""

# Project 2 - Dice Rolling Simulator
import random

user_input = input("Press y to roll the dice or n to exit: ")

while user_input == "y":
    no = random.randint(1, 6)

    if no == 1:
        print("[-----]")
        print("[     ]")
        print("[  0  ]")
        print("[     ]")
        print("[-----]")

    if no == 2:
        print("[-----]")
        print("[ 0   ]")
        print("[     ]")
        print("[   0 ]")
        print("[-----]")

    if no == 3:
        print("[-----]")
        print("[ 0   ]")
        print("[  0  ]")
        print("[   0 ]")
        print("[-----]")

    if no == 4:
        print("[-----]")
        print("[ 0 0 ]")
        print("[     ]")
        print("[ 0 0 ]")
        print("[-----]")

    if no == 5:
        print("[-----]")
        print("[ 0 0 ]")
        print("[  0  ]")
        print("[ 0 0 ]")
        print("[-----]")

    if no == 6:
        print("[-----]")
        print("[ 0 0 ]")
        print("[ 0 0 ]")
        print("[ 0 0 ]")
        print("[-----]")

    user_input = input("Press y to roll again or n to exit: ")

